### ISSUE TITLE
Attempt to make METviewer work with Singularity.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/container-dtc-nwp#18]
The container-dtc-nwp tutorial instructions have been updated to use singularity:
   https://dtcenter.org/nwp-containers-online-tutorial/introduction

However the "docker-compose" step for METviewer does not yet work.
This task is to test and hopefully fix METviewer to work with singularity.

**Comment by mkavulich** [comment]
**So here is my progress/notes/rants on getting a docker-compose equivalent to work for Singularity**

Docker-compose does not have a native singularity equivalent, but there is a workaround: https://singularityhub.github.io/singularity-compose/

**Cheyenne**
Singularity is available on Cheyenne, with a simple "module load":
`module load singularity/3.5.3`

Unfortunately, I don't believe there is a way to get the singularity-compose functionality to work on Cheyenne. Because it is a bit of a hack, it requires downloading some python tools (no problem there) and then building a special Singularity container (PROBLEM!). 

The first thing I tried was a remote build (https://cloud.sylabs.io/builder). However, for remote builds, singularity can not upload additional files beyond the singularity recipe file (https://github.com/hpcng/singularity/issues/4455), which causes singularity-compose to fail to build.

Next I tried the option of building with "fakeroot" (https://github.com/hpcng/singularity/issues/4507). Fakeroot does not work on Cheyenne due to how user permissions are set up. 

**Vagrant VM**

The Vagrant virtual machine is the recommended software for installing Singularity on MacOS (https://sylabs.io/guides/3.5/admin-guide/installation.html#mac). I found this easy, though the default Vagrantfile (recipe file for virtual machine) needed some modification.
I had to resize default machine from 20GB to 100GB (https://marcbrandner.com/blog/increasing-disk-space-of-a-linux-based-vagrant-box-on-provisioning/) and also increase the number of processors (default is 1). This is the Vagrantfile I used:

```Vagrant.configure("2") do |config|

  config.vm.box = "sylabs/singularity-3.5-ubuntu-bionic64"
  config.disksize.size = '100GB'
  config.vm.provider "virtualbox" do |v|
    v.cpus = 4
  end

end```

In this Vagrant VM I was able to run the entire tutorial in Singularity up to MetViewer. Here is where I hit the limit of my knowledge...I could not quite get singularity-compose to behave the way I expected. I installed singularity-compose through pip3 and built the container the way it was described. I also made a copy of the docker-compose.yml file as singularity-compose.yml, and `singularity-compose up` output no errors, but the running of the MetViewer container failed:

```
singularity exec -B ${PROJ_DIR}/container-dtc-nwp/components/scripts/common:/home/scripts/common -B ${PROJ_DIR}/container-dtc-nwp/components/scripts/sandy_20121027:/home/scripts/case -B ${CASE_DIR}/metprd:/home/metprd ~/metviewer_2.11.sif /home/scripts/common/metv_load_all.ksh mv_sandy
ERROR 2005 (HY000): Unknown MySQL server host 'mysql_mv' (2)
ERROR 2005 (HY000): Unknown MySQL server host 'mysql_mv' (2)
/home/scripts/common/metv_load_all.ksh[31]: /METviewer/sql/mv_mysql.sql: cannot open [Permission denied]
/home/scripts/common/metv_load_all.ksh[34]: /data/load_mv_sandy.xml: cannot create [No such file or directory]
/home/scripts/common/metv_load_all.ksh[38]: /METviewer/bin/mv_load.sh: cannot execute [Permission denied]
cat: /scripts/common/load_metv_TMPL.xml: No such file or directory
```
So that's where we are now. Let me know if you need more info.

**Comment by JohnHalleyGotway** [comment]
Running Singularity on a Mac:
https://sylabs.io/guides/3.0/user-guide/installation.html#install-on-windows-or-mac

Step 1: Install Vagrant. It's available via Homebrew, but not Macports (which SNAT prefers me to use). Download/install a MAC dmg from
   https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_x86_64.dmg

Step 2: Download/install Vagrant virtual box for Mac from
   https://download.virtualbox.org/virtualbox/6.1.14/VirtualBox-6.1.14-140239-OSX.dmg

Step 3: Run Vagrant:
```
# Create working area
mkdir vm-singularity && cd vm-singularity
# Cleanup any existing vm's
vagrant destroy && rm Vagrantfile
# Launch a new vm
export VM=sylabs/singularity-3.0-ubuntu-bionic64 && \
    vagrant init $VM && vagrant up && vagrant ssh
```

**Comment by JohnHalleyGotway** [comment]
Shifting gears. Instead of trying to run this locally on a Mac, try running singularity-compose on AWS.
Follow the tutorial instructions here:
https://dtcenter.org/nwp-containers-online-tutorial/introduction

**Comment by JohnHalleyGotway** [comment]
I've attached the singularity-compose.yml file that was closest to working on AWS.
[singularity-compose.yml.txt](https://github.com/NCAR/container-dtc-nwp/files/5308260/singularity-compose.yml.txt)

**Comment by JohnHalleyGotway** [comment]
Closing this issue and deleting the corresponding feature branch. It was not successful.
