### ISSUE TITLE
Provide shapefiles for Python plotting

### ISSUE THREAD

**Issue by michelleharrold** [NCAR/container-dtc-nwp#56]
The Python plotting capabilities require shapefiles. If shapefiles are not in the designated area, an attempt to download them is made. For example, one of the [files ](https://naciscdn.org/naturalearth/50m/physical/ne_50m_lakes.zip) is not currently available (or the location has been updated), so it causes the Python plotting scripts to error and fail, if the file has not been previously downloaded.

A proposed fix is to provide the shapefile data similar to how we provide the WPS geog, CRTM files, model input, and obs data. This would require changes to the run_python.ksh script as well as the run command.

**Comment by JohnHalleyGotway** [comment]
@michelleharrold this seems like a good solution to me that's consistent with existing logic for handling external data files.

If the shapefiles were trivially small, we could consider bundling them into the python image as defined by its [Dockerfile](https://github.com/NCAR/container-dtc-nwp/blob/main/components/python/Dockerfile). But I'm guessing that they're not that small.

Along with the run_python.ksh script and run commands (e.g. for [Sandy](https://dtcenter.org/nwp-containers-online-tutorial/hurricane-sandy-case-27-oct-2012/create-graphics)), we'd also need to update the static/initialization download [instructions](https://dtcenter.org/nwp-containers-online-tutorial/downloading-input-data).

**Comment by michelleharrold** [comment]
@JohnHalleyGotway - thanks for weighing in! What would you consider trivially small? They are smaller than I thought (6M).

**Comment by JohnHalleyGotway** [comment]
@michelleharrold well that certainly is smaller than the WPS_GEOG (1.5 G), gsi (1.4 G), model (431 M), and observation (1.0 G) datasets! So bundling it into the image is an option.

The downside of that is that we're essentially "hard-coding" the background map datasets. There are multiple resolutions of the [Natural Earth shapefiles](https://www.naturalearthdata.com/downloads/), from large files for fine-scale detail to smaller files for lower-resolution data. Mounting the shapefile data as a directory at runtime would provide the flexibility of swapping out different resolutions (or perhaps sources of shapefiles... although the [ALL_plot_allvars.py](https://github.com/NCAR/container-dtc-nwp/blob/main/components/scripts/common/python/ALL_plot_allvars.py) seems to be rather particular about naming conventions. That flexibility may become more important if/when these containers are applied more frequently to different areas of the globe. For that reason, I'd vote for serving them up via an external dataset rather than bundling them with the image.
